service: abarba-me

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  versionFunctions: false

functions:
  web:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /img/{proxy+}
          method: get
          contentHandling: CONVERT_TO_BINARY
      - http:
          path: /{proxy+}
          method: get
